parameters:
  external_feed: ''
  pypi_remote: ''
  dependsOn: []

jobs:
- job: publish
  dependsOn: ${{ parameters.dependsOn }}
  condition: succeeded()
  pool: {vmImage: 'ubuntu-latest'}
  variables:
    TMPDIR: $(Build.BinariesDirectory)
    PIP_NO_WARN_SCRIPT_LOCATION: '0'
  steps:
  - task: UsePythonVersion@0
    displayName: setup python3.7
    inputs: {versionSpec: '3.7'}
  - task: TwineAuthenticate@0
    inputs:
      externalFeeds: ${{ parameters.external_feed}}
  - script: 'python -m pip install -U --user --force-reinstall twine pep517'
    displayName: "acquire build tools"
  - script: 'python -m pep517.build --binary --source --out-dir "$(System.DefaultWorkingDirectory)/w" .'
    displayName: "build wheel and source distribution"
  - script:  ${{ format('python3.7 -m twine upload -r {0} --config-file $(PYPIRC_PATH) "$(System.DefaultWorkingDirectory)/w/*"', parameters.pypi_remote) }}
    displayName: "upload sdist and wheel to PyPi"
